[workspace]
authors = ["Noah Jutz <noah@noahjutz.com>"]
channels = ["https://prefix.dev/robostack-humble", "https://prefix.dev/conda-forge"]
name = "ros_ws"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dependencies]
ros-humble-ros2run = ">=0.18.12,<0.19"
ros-humble-my-python-ros-pkg = { path = "src/my_python_ros_pkg" }
ros-humble-my-cmake-ros-pkg = { path = "src/my_cmake_ros_pkg" }
